### ISSUE TITLE
When import data via csv lyricist is imported rather than arranger

### ISSUE THREAD

**Issue by cpalop** [matijakolaric-com/django-music-publisher#49]
I'm importing data via CSV but, I write arranger or Ar on Writer Role and Lyricist is saved after successful import.

**Comment by matijakolaric** [comment]
From user manual:
_Writer Role must start with one of C, A, CA, AR, TR or AD, e.g. C - Composer._

"AR" and "Ar" are not the same thing, well, not in civilised systems anyway.
