### ISSUE TITLE
The value type needs to be converted

### ISSUE THREAD

**Issue by Huanghibo** [matijakolaric-com/django-music-publisher#64]
**Describe the bug**
#  templatetags/cwr_generators.py
# line: 46，The value type needs to be converted
``` 
value = str(value).rjust(3, "0") 
```
**Version and deployment**
Which version is installed and how it is deployed. Note that we only fix bugs in the latest stable version / master branch.
V.23.4
**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
You must copy-paste application log that shows the error. On Heroku, you can access it through Heroku dashboard.

**Additional context**

**Comment by matijakolaric** [comment]
Not sure what the bug is here. Nor how to reproduce.
